name: sa4i
version: 0.0.0
synopsis: A proof of concept
description: An application which utilizes actuarial concepts to solve a pressing risk management problem related to insurance.

language: GHC2021

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - LambdaCase
  - NoStarIsType
  - OverloadedStrings
  - TemplateHaskell
  - TypeFamilies
  - DefaultSignatures
  - UndecidableInstances

dependencies:
  - finite-typelits
  - ghc-typelits-knownnat
  - ghc-typelits-natnormalise
  - base
  - large-anon
  - vector
  - bytestring
  - text
  - string-interpolate
  - formatting
  - http-conduit

library:
   source-dirs: src
   ghc-options: 
     - -fplugin=Data.Record.Anon.Plugin 
     - -fplugin=GHC.TypeLits.KnownNat.Solver
     - -fplugin=GHC.TypeLits.Normalise

#executables:
#  sa4i-go:
#    main: Main.hs
#    source-dirs: app

